name: collaguazo_examen
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  sqflite: ^2.3.3+1
  google_maps_flutter: ^2.5.3
  google_maps_flutter_web: ^0.5.4+3
  geolocator: ^10.0.0
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/candado.png
  uses-material-design: true

